{% set version = "0.3.0" %}

package:
  name: stglib
  version: {{ version }}

source:
  url: https://github.com/dnowacki-usgs/stglib/archive/v{{ version }}.tar.gz
  sha256: 3c20bb5582e769ef1d6950c156b4a1446c47fa0c117e17f2a8610e6970db4828

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - compliance-checker
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - pytest
    - pyyaml
    - scipy
    - sqlite
    - xarray
    - xmltodict

test:
  imports:
    - stglib
  commands:
    - runaqdhdr2cdf.py --help

about:
  home: http://github.com/USGS-CMG/stglib
  license: CC0
  license_file: LICENSE.md
  license_family: CC
  summary: 'Process data from a variety of oceanographic instrumentation'
  description: |
    This package contains code to process data from a variety of oceanographic
    instrumentation, consistent with the procedures of the USGS Coastal/Marine
    Hazards and Resources Program (formerly Coastal and Marine Geology Program).
  doc_url: http://stglib.readthedocs.io/
  dev_url: https://github.com/USGS-CMG/stglib

extra:
  recipe-maintainers:
    - dnowacki-usgs
