{% set version = "0.5.0" %}

package:
  name: stglib
  version: {{ version }}

source:
  url: https://github.com/dnowacki-usgs/stglib/archive/v{{ version }}.tar.gz
  sha256: 253e952fafa980fa2d94dabf2b3948c7e4f402e304a43f9da9cd8367a4bee881

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - compliance-checker
    - git-lfs
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - pre-commit
    - pyarrow
    - pytest
    - pyyaml
    - scipy
    - seawater
    - sqlite
    - tqdm
    - xarray
    - xmltodict

test:
  imports:
    - stglib
  commands:
    - runaqdhdr2cdf.py --help

about:
  home: http://github.com/USGS-CMG/stglib
  license: CC0
  license_file: LICENSE.md
  license_family: CC
  summary: Process data from a variety of oceanographic instrumentation
  description: |
    This package contains code to process data from a variety of oceanographic
    instrumentation, consistent with the procedures of the USGS Coastal/Marine
    Hazards and Resources Program (formerly Coastal and Marine Geology Program).
  doc_url: http://stglib.readthedocs.io/
  dev_url: https://github.com/USGS-CMG/stglib

extra:
  recipe-maintainers:
    - dnowacki-usgs
