{% set version = "0.9.4" %}

package:
  name: stglib
  version: {{ version }}

source:
  url: https://github.com/USGS-CMG/stglib/archive/v{{ version }}.tar.gz
  sha256: 4500f2f410ba8a7f526e86c9994d4254513972ff3f5633fe696f755de77ebbd6

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - runsigmat2cdf = stglib.core.cmd:runsigmat2cdf
    - runsigcdf2nc = stglib.core.cmd:runsigcdf2nc

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - compliance-checker
    - dolfyn
    - git-lfs
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - pre-commit
    - pyarrow
    - pytest
    - pyyaml
    - scipy
    - seawater
    - sqlite
    - tqdm
    - xarray
    - xmltodict

test:
  imports:
    - stglib
  commands:
    - runaqdhdr2cdf.py --help

about:
  home: http://github.com/USGS-CMG/stglib
  license: CC-PDDC
  license_file: LICENSE.md
  license_family: CC
  summary: Process data from a variety of oceanographic instrumentation
  description: |
    This package contains code to process data from a variety of oceanographic
    instrumentation, consistent with the procedures of the USGS Coastal/Marine
    Hazards and Resources Program (formerly Coastal and Marine Geology Program).
  doc_url: http://stglib.readthedocs.io/
  dev_url: https://github.com/USGS-CMG/stglib

extra:
  recipe-maintainers:
    - dnowacki-usgs
