{% set version = "0.9.0" %}

package:
  name: stglib
  version: {{ version }}

source:
  url: https://github.com/USGS-CMG/stglib/archive/v{{ version }}.tar.gz
  sha256: a789acb85a3eaa08b85f7e55b8e5309fa77771ebfbc549ffd471d627efa5b837

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - compliance-checker
    - dolfyn
    - git-lfs
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - pre-commit
    - pyarrow
    - pytest
    - pyyaml
    - scipy
    - seawater
    - sqlite
    - tqdm
    - xarray
    - xmltodict

test:
  imports:
    - stglib
  commands:
    - runaqdhdr2cdf.py --help

about:
  home: http://github.com/USGS-CMG/stglib
  license: CC-PDDC
  license_file: LICENSE.md
  license_family: CC
  summary: Process data from a variety of oceanographic instrumentation
  description: |
    This package contains code to process data from a variety of oceanographic
    instrumentation, consistent with the procedures of the USGS Coastal/Marine
    Hazards and Resources Program (formerly Coastal and Marine Geology Program).
  doc_url: http://stglib.readthedocs.io/
  dev_url: https://github.com/USGS-CMG/stglib

extra:
  recipe-maintainers:
    - dnowacki-usgs
