{% set version = "0.2.2" %}

package:
  name: stglib
  version: {{ version }}

source:
  url: https://github.com/dnowacki-usgs/stglib/archive/v{{ version }}.tar.gz
  sha256: 4246579ac96dee6f1e5fb47822ed2ccd4cf42f15e099c9bd0556a97f2064af67

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - pyyaml
    - scipy
    - sqlite
    - xarray
    - xmltodict

test:
  imports:
    - stglib
  commands:
    - runaqdhdr2cdf.py --help

about:
  home: http://github.com/dnowacki-usgs/stglib
  license: CC0
  license_file: LICENSE.md
  license_family: CC
  summary: 'Process data from a variety of oceanographic instrumentation'
  description: |
    This package contains code to process data from a variety of oceanographic
    instrumentation, consistent with the procedures of the Sediment Transport
    Group at the USGS Woods Hole Coastal and Marine Science Center.
  doc_url: http://stglib.readthedocs.io/
  dev_url: https://github.com/dnowacki-usgs/stglib

extra:
  recipe-maintainers:
    - dnowacki-usgs
